# Generated by Django 3.2.16 on 2023-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('song_duration', models.CharField(max_length=100)),
                ('song_author', models.CharField(max_length=100)),
                ('song_classification', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
