# Generated by Django 3.2.16 on 2023-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooksmodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='onlinebooksmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
