# Generated by Django 3.2.16 on 2023-05-27 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfavoritemusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavoritemusic',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
