# Generated by Django 3.2.16 on 2023-05-31 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfavoritemusic', '0002_myfavoritemusic_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavoritemusic',
            name='song_duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
