# Generated by Django 3.2.16 on 2023-05-21 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='offline_book_images/'),
            preserve_default=False,
        ),
    ]
