# Generated by Django 3.2.16 on 2023-08-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game_leval', models.CharField(max_length=100)),
                ('record_score', models.IntegerField()),
                ('record_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('snake_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snake', to='users.myuser')),
            ],
        ),
    ]
