# Generated by Django 3.2.16 on 2023-04-05 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('record_user_borrow_time', models.IntegerField(max_length=100)),
                ('record_user_borrow_deadline', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('record_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_record', to='users.myuser')),
            ],
        ),
    ]
