# Generated by Django 3.2.16 on 2023-11-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_articlepost_collects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavoriteArtile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('favorite_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article_id', to='article.articlepost')),
                ('favorite_article_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_article_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
