# Generated by Django 3.2.16 on 2023-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotteryprize',
            name='image',
            field=models.ImageField(upload_to='lottery_prizes/'),
        ),
    ]
